### PR TITLE
http: Initialize http.Request with ctx so cancelation interrupts the request

### LINKED ISSUE #320: context is not respected for HTTP requests
It seems the passed `Ctx` to `getter.Client` is not passed to the `http.Request`:

https://github.com/hashicorp/go-getter/blob/main/get_http.go#L85-L94

I wrote a test for this below. I receive the context.Canceled error, but it still waits for both requests (HEAD + GET) to finish, thus this test takes 6 seconds instead of <1sec.

```go
package cache

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/hashicorp/go-getter"
)

func TestHashicorpGoGetter__RespectsContextCanceled(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel() // cancel immediately

	srv := GivenHTTPServer(t, http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		t.Logf("Received %s %s", req.Method, req.URL)
		time.Sleep(3 * time.Second)
	}))

	tmpdir := t.TempDir()
	g := getter.Client{
		Ctx:  ctx,
		Src:  srv.URL,
		Pwd:  tmpdir,
		Dst:  "testfile",
		Mode: getter.ClientModeFile,
	}

	t1 := time.Now()
	err := g.Get()
	dur := time.Since(t1)

	if !errors.Is(err, context.Canceled) {
		t.Log("error is not context.Canceled")
		t.Fail()
	}
	if dur > 1*time.Second {
		t.Log("Get() took too long")
		t.Fail()
	}
}

func GivenHTTPServer(t testing.TB, h http.Handler) *httptest.Server {
	srv := httptest.NewServer(h)
	t.Cleanup(func() {
		srv.CloseClientConnections()
		srv.Close()
	})
	return srv
}
```

Obviously it is more realistic to cancel the context during the request. This could be achieved by moving the `cancel()` call into the http handler.

### PR DESCRIPTION
**Pull request by zeisss**
Fixes #320

I tried following the structure in the existing tests. I will create a separate PR for the `v2` branch.

### CODE REVIEW

File: get_http_test.go [hunk 1]
```diff
@@ -404,6 +406,35 @@ func TestHttpGetter_cleanhttp(t *testing.T) {
...
+
+	start := time.Now()
+	err := g.Get(dst, &u)
+	dur := time.Since(start)
+
+	if !errors.Is(err, context.Canceled) {
+		t.Fatalf("expected context.Canceled, got: %v", err)
+	}
+	if dur > 1*time.Second {
+		t.Fatal("Get() took too long")
```
Comment (azr) [inline get_http_test.go:434]: This test might get flaky with CI tools and I think that the http client will return before actually sending the request, so the err check should be enough IMO.
If you agree then let's remove it ?

Comment (zeisss) [reply get_http_test.go:434]: At least in my production code I got the context.Canceled due to the copy operations later aborting and returning the context.Canceled. 
The important part here is that we use the `ctx` in the `http.Request`. We could write our own mock http.RoundTripper and test the context there, but I am not sure if that isn't too focused.

**Review by azr — APPROVED** [review]
Hello there, thanks for opening so quickly, this LGTM, just had a suggestion for tests.

Also, I think you need to sign the cla before we can merge this one 🙂

File: get_http_test.go (hunk 1 above)
Comment (azr) [reply get_http_test.go:434]: I was trying to say that time-bound testing is not always a good way to test because often: ci tools are shared instances, and sometimes they can just randomly freeze for a (possibly long) moment.

Comment (zeisss) [reply get_http_test.go:434]: > and sometimes they can just randomly freeze for a (possibly long) moment.

Agreed. I will rework the code a bit to explicitly check in the transport or sthg. Stay tuned 👍

Comment (azr) [reply get_http_test.go:434]: But the above tests line #430 sorts of guarantees that this is valid, because the error has to be a `context.Canceled` one.

**Comment by azr** [comment]
No worries, I see only one notification on GH 🙂, good findings !

**Comment by zeisss** [comment]
@azr I have signed the CLA now.

Regarding the tests: I have added a workaround by introspecting the request passed to the transport. If you don't want that nuance I can drop it. Otherwise this should be ready to go. Please take a look.

**Review by azr — APPROVED** [review]
Cool beans ! This looks good to me, thanks.
